// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transaction.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_transaction_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_transaction_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "node.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_transaction_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_transaction_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_transaction_2eproto;
namespace proto {
class Column;
class ColumnDefaultTypeInternal;
extern ColumnDefaultTypeInternal _Column_default_instance_;
class Row;
class RowDefaultTypeInternal;
extern RowDefaultTypeInternal _Row_default_instance_;
class Transaction;
class TransactionDefaultTypeInternal;
extern TransactionDefaultTypeInternal _Transaction_default_instance_;
}  // namespace proto
PROTOBUF_NAMESPACE_OPEN
template<> ::proto::Column* Arena::CreateMaybeMessage<::proto::Column>(Arena*);
template<> ::proto::Row* Arena::CreateMaybeMessage<::proto::Row>(Arena*);
template<> ::proto::Transaction* Arena::CreateMaybeMessage<::proto::Transaction>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace proto {

enum Result : int {
  Fail = 0,
  Success = 1,
  Result_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  Result_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool Result_IsValid(int value);
constexpr Result Result_MIN = Fail;
constexpr Result Result_MAX = Success;
constexpr int Result_ARRAYSIZE = Result_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Result_descriptor();
template<typename T>
inline const std::string& Result_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Result>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Result_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Result_descriptor(), enum_t_value);
}
inline bool Result_Parse(
    const std::string& name, Result* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Result>(
    Result_descriptor(), name, value);
}
enum TxnType : int {
  ClientTxn = 0,
  ShardedClientTxn = 1,
  EpochShardEndFlag = 2,
  RemoteServerTxn = 3,
  EpochRemoteServerEndFlag = 4,
  BackUpTxn = 5,
  EpochBackUpEndFlag = 6,
  CommittedTxn = 7,
  EpochCommittedTxnEndFlag = 8,
  AbortSet = 20,
  InsertSet = 21,
  EpochShardACK = 30,
  EpochRemoteServerACK = 31,
  BackUpACK = 32,
  AbortSetACK = 33,
  InsertSetACK = 34,
  EpochLogPushDownComplete = 35,
  NullMark = 40,
  Lock_ok = 51,
  Lock_abort = 52,
  Prepare_req = 53,
  Prepare_ok = 54,
  Prepare_abort = 55,
  Commit_req = 56,
  Commit_ok = 57,
  Commit_abort = 58,
  Abort_txn = 59,
  TxnType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  TxnType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool TxnType_IsValid(int value);
constexpr TxnType TxnType_MIN = ClientTxn;
constexpr TxnType TxnType_MAX = Abort_txn;
constexpr int TxnType_ARRAYSIZE = TxnType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* TxnType_descriptor();
template<typename T>
inline const std::string& TxnType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, TxnType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function TxnType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    TxnType_descriptor(), enum_t_value);
}
inline bool TxnType_Parse(
    const std::string& name, TxnType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<TxnType>(
    TxnType_descriptor(), name, value);
}
enum TxnState : int {
  Empty = 0,
  Abort = 1,
  Commit = 2,
  TxnState_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  TxnState_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool TxnState_IsValid(int value);
constexpr TxnState TxnState_MIN = Empty;
constexpr TxnState TxnState_MAX = Commit;
constexpr int TxnState_ARRAYSIZE = TxnState_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* TxnState_descriptor();
template<typename T>
inline const std::string& TxnState_Name(T enum_t_value) {
  static_assert(::std::is_same<T, TxnState>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function TxnState_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    TxnState_descriptor(), enum_t_value);
}
inline bool TxnState_Parse(
    const std::string& name, TxnState* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<TxnState>(
    TxnState_descriptor(), name, value);
}
enum OpType : int {
  Read = 0,
  Insert = 1,
  Update = 2,
  Delete = 3,
  OpType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  OpType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool OpType_IsValid(int value);
constexpr OpType OpType_MIN = Read;
constexpr OpType OpType_MAX = Delete;
constexpr int OpType_ARRAYSIZE = OpType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* OpType_descriptor();
template<typename T>
inline const std::string& OpType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, OpType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function OpType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    OpType_descriptor(), enum_t_value);
}
inline bool OpType_Parse(
    const std::string& name, OpType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<OpType>(
    OpType_descriptor(), name, value);
}
// ===================================================================

class Column :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:proto.Column) */ {
 public:
  Column();
  virtual ~Column();

  Column(const Column& from);
  Column(Column&& from) noexcept
    : Column() {
    *this = ::std::move(from);
  }

  inline Column& operator=(const Column& from) {
    CopyFrom(from);
    return *this;
  }
  inline Column& operator=(Column&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Column& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Column* internal_default_instance() {
    return reinterpret_cast<const Column*>(
               &_Column_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Column& a, Column& b) {
    a.Swap(&b);
  }
  inline void Swap(Column* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Column* New() const final {
    return CreateMaybeMessage<Column>(nullptr);
  }

  Column* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Column>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Column& from);
  void MergeFrom(const Column& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Column* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "proto.Column";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_transaction_2eproto);
    return ::descriptor_table_transaction_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kValueFieldNumber = 2,
    kIdFieldNumber = 1,
  };
  // bytes value = 2;
  void clear_value();
  const std::string& value() const;
  void set_value(const std::string& value);
  void set_value(std::string&& value);
  void set_value(const char* value);
  void set_value(const void* value, size_t size);
  std::string* mutable_value();
  std::string* release_value();
  void set_allocated_value(std::string* value);
  private:
  const std::string& _internal_value() const;
  void _internal_set_value(const std::string& value);
  std::string* _internal_mutable_value();
  public:

  // uint32 id = 1;
  void clear_id();
  ::PROTOBUF_NAMESPACE_ID::uint32 id() const;
  void set_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_id() const;
  void _internal_set_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:proto.Column)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr value_;
  ::PROTOBUF_NAMESPACE_ID::uint32 id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_transaction_2eproto;
};
// -------------------------------------------------------------------

class Row :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:proto.Row) */ {
 public:
  Row();
  virtual ~Row();

  Row(const Row& from);
  Row(Row&& from) noexcept
    : Row() {
    *this = ::std::move(from);
  }

  inline Row& operator=(const Row& from) {
    CopyFrom(from);
    return *this;
  }
  inline Row& operator=(Row&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Row& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Row* internal_default_instance() {
    return reinterpret_cast<const Row*>(
               &_Row_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Row& a, Row& b) {
    a.Swap(&b);
  }
  inline void Swap(Row* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Row* New() const final {
    return CreateMaybeMessage<Row>(nullptr);
  }

  Row* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Row>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Row& from);
  void MergeFrom(const Row& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Row* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "proto.Row";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_transaction_2eproto);
    return ::descriptor_table_transaction_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kColumnFieldNumber = 5,
    kTableNameFieldNumber = 2,
    kKeyFieldNumber = 3,
    kDataFieldNumber = 4,
    kCsnFieldNumber = 6,
    kOpTypeFieldNumber = 1,
  };
  // repeated .proto.Column column = 5;
  int column_size() const;
  private:
  int _internal_column_size() const;
  public:
  void clear_column();
  ::proto::Column* mutable_column(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::proto::Column >*
      mutable_column();
  private:
  const ::proto::Column& _internal_column(int index) const;
  ::proto::Column* _internal_add_column();
  public:
  const ::proto::Column& column(int index) const;
  ::proto::Column* add_column();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::proto::Column >&
      column() const;

  // string table_name = 2;
  void clear_table_name();
  const std::string& table_name() const;
  void set_table_name(const std::string& value);
  void set_table_name(std::string&& value);
  void set_table_name(const char* value);
  void set_table_name(const char* value, size_t size);
  std::string* mutable_table_name();
  std::string* release_table_name();
  void set_allocated_table_name(std::string* table_name);
  private:
  const std::string& _internal_table_name() const;
  void _internal_set_table_name(const std::string& value);
  std::string* _internal_mutable_table_name();
  public:

  // bytes key = 3;
  void clear_key();
  const std::string& key() const;
  void set_key(const std::string& value);
  void set_key(std::string&& value);
  void set_key(const char* value);
  void set_key(const void* value, size_t size);
  std::string* mutable_key();
  std::string* release_key();
  void set_allocated_key(std::string* key);
  private:
  const std::string& _internal_key() const;
  void _internal_set_key(const std::string& value);
  std::string* _internal_mutable_key();
  public:

  // bytes data = 4;
  void clear_data();
  const std::string& data() const;
  void set_data(const std::string& value);
  void set_data(std::string&& value);
  void set_data(const char* value);
  void set_data(const void* value, size_t size);
  std::string* mutable_data();
  std::string* release_data();
  void set_allocated_data(std::string* data);
  private:
  const std::string& _internal_data() const;
  void _internal_set_data(const std::string& value);
  std::string* _internal_mutable_data();
  public:

  // uint64 csn = 6;
  void clear_csn();
  ::PROTOBUF_NAMESPACE_ID::uint64 csn() const;
  void set_csn(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_csn() const;
  void _internal_set_csn(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // .proto.OpType op_type = 1;
  void clear_op_type();
  ::proto::OpType op_type() const;
  void set_op_type(::proto::OpType value);
  private:
  ::proto::OpType _internal_op_type() const;
  void _internal_set_op_type(::proto::OpType value);
  public:

  // @@protoc_insertion_point(class_scope:proto.Row)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::proto::Column > column_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr table_name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr key_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr data_;
  ::PROTOBUF_NAMESPACE_ID::uint64 csn_;
  int op_type_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_transaction_2eproto;
};
// -------------------------------------------------------------------

class Transaction :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:proto.Transaction) */ {
 public:
  Transaction();
  virtual ~Transaction();

  Transaction(const Transaction& from);
  Transaction(Transaction&& from) noexcept
    : Transaction() {
    *this = ::std::move(from);
  }

  inline Transaction& operator=(const Transaction& from) {
    CopyFrom(from);
    return *this;
  }
  inline Transaction& operator=(Transaction&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Transaction& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Transaction* internal_default_instance() {
    return reinterpret_cast<const Transaction*>(
               &_Transaction_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Transaction& a, Transaction& b) {
    a.Swap(&b);
  }
  inline void Swap(Transaction* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Transaction* New() const final {
    return CreateMaybeMessage<Transaction>(nullptr);
  }

  Transaction* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Transaction>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Transaction& from);
  void MergeFrom(const Transaction& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Transaction* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "proto.Transaction";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_transaction_2eproto);
    return ::descriptor_table_transaction_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRowFieldNumber = 1,
    kTxnServerIpFieldNumber = 13,
    kClientIpFieldNumber = 15,
    kStorageTypeFieldNumber = 22,
    kStartEpochFieldNumber = 2,
    kCommitEpochFieldNumber = 3,
    kCsnFieldNumber = 4,
    kTxnTypeFieldNumber = 5,
    kTxnStateFieldNumber = 6,
    kMessageServerIdFieldNumber = 10,
    kShardIdFieldNumber = 11,
    kShardServerIdFieldNumber = 12,
    kClientTxnIdFieldNumber = 16,
    kTxnServerIdFieldNumber = 14,
    kStorageTotalNumFieldNumber = 21,
  };
  // repeated .proto.Row row = 1;
  int row_size() const;
  private:
  int _internal_row_size() const;
  public:
  void clear_row();
  ::proto::Row* mutable_row(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::proto::Row >*
      mutable_row();
  private:
  const ::proto::Row& _internal_row(int index) const;
  ::proto::Row* _internal_add_row();
  public:
  const ::proto::Row& row(int index) const;
  ::proto::Row* add_row();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::proto::Row >&
      row() const;

  // string txn_server_ip = 13;
  void clear_txn_server_ip();
  const std::string& txn_server_ip() const;
  void set_txn_server_ip(const std::string& value);
  void set_txn_server_ip(std::string&& value);
  void set_txn_server_ip(const char* value);
  void set_txn_server_ip(const char* value, size_t size);
  std::string* mutable_txn_server_ip();
  std::string* release_txn_server_ip();
  void set_allocated_txn_server_ip(std::string* txn_server_ip);
  private:
  const std::string& _internal_txn_server_ip() const;
  void _internal_set_txn_server_ip(const std::string& value);
  std::string* _internal_mutable_txn_server_ip();
  public:

  // string client_ip = 15;
  void clear_client_ip();
  const std::string& client_ip() const;
  void set_client_ip(const std::string& value);
  void set_client_ip(std::string&& value);
  void set_client_ip(const char* value);
  void set_client_ip(const char* value, size_t size);
  std::string* mutable_client_ip();
  std::string* release_client_ip();
  void set_allocated_client_ip(std::string* client_ip);
  private:
  const std::string& _internal_client_ip() const;
  void _internal_set_client_ip(const std::string& value);
  std::string* _internal_mutable_client_ip();
  public:

  // string storage_type = 22;
  void clear_storage_type();
  const std::string& storage_type() const;
  void set_storage_type(const std::string& value);
  void set_storage_type(std::string&& value);
  void set_storage_type(const char* value);
  void set_storage_type(const char* value, size_t size);
  std::string* mutable_storage_type();
  std::string* release_storage_type();
  void set_allocated_storage_type(std::string* storage_type);
  private:
  const std::string& _internal_storage_type() const;
  void _internal_set_storage_type(const std::string& value);
  std::string* _internal_mutable_storage_type();
  public:

  // uint64 start_epoch = 2;
  void clear_start_epoch();
  ::PROTOBUF_NAMESPACE_ID::uint64 start_epoch() const;
  void set_start_epoch(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_start_epoch() const;
  void _internal_set_start_epoch(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 commit_epoch = 3;
  void clear_commit_epoch();
  ::PROTOBUF_NAMESPACE_ID::uint64 commit_epoch() const;
  void set_commit_epoch(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_commit_epoch() const;
  void _internal_set_commit_epoch(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 csn = 4;
  void clear_csn();
  ::PROTOBUF_NAMESPACE_ID::uint64 csn() const;
  void set_csn(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_csn() const;
  void _internal_set_csn(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // .proto.TxnType txn_type = 5;
  void clear_txn_type();
  ::proto::TxnType txn_type() const;
  void set_txn_type(::proto::TxnType value);
  private:
  ::proto::TxnType _internal_txn_type() const;
  void _internal_set_txn_type(::proto::TxnType value);
  public:

  // .proto.TxnState txn_state = 6;
  void clear_txn_state();
  ::proto::TxnState txn_state() const;
  void set_txn_state(::proto::TxnState value);
  private:
  ::proto::TxnState _internal_txn_state() const;
  void _internal_set_txn_state(::proto::TxnState value);
  public:

  // uint64 message_server_id = 10;
  void clear_message_server_id();
  ::PROTOBUF_NAMESPACE_ID::uint64 message_server_id() const;
  void set_message_server_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_message_server_id() const;
  void _internal_set_message_server_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 shard_id = 11;
  void clear_shard_id();
  ::PROTOBUF_NAMESPACE_ID::uint64 shard_id() const;
  void set_shard_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_shard_id() const;
  void _internal_set_shard_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 shard_server_id = 12;
  void clear_shard_server_id();
  ::PROTOBUF_NAMESPACE_ID::uint64 shard_server_id() const;
  void set_shard_server_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_shard_server_id() const;
  void _internal_set_shard_server_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 client_txn_id = 16;
  void clear_client_txn_id();
  ::PROTOBUF_NAMESPACE_ID::uint64 client_txn_id() const;
  void set_client_txn_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_client_txn_id() const;
  void _internal_set_client_txn_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint32 txn_server_id = 14;
  void clear_txn_server_id();
  ::PROTOBUF_NAMESPACE_ID::uint32 txn_server_id() const;
  void set_txn_server_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_txn_server_id() const;
  void _internal_set_txn_server_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint64 storage_total_num = 21;
  void clear_storage_total_num();
  ::PROTOBUF_NAMESPACE_ID::uint64 storage_total_num() const;
  void set_storage_total_num(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_storage_total_num() const;
  void _internal_set_storage_total_num(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // @@protoc_insertion_point(class_scope:proto.Transaction)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::proto::Row > row_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr txn_server_ip_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr client_ip_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr storage_type_;
  ::PROTOBUF_NAMESPACE_ID::uint64 start_epoch_;
  ::PROTOBUF_NAMESPACE_ID::uint64 commit_epoch_;
  ::PROTOBUF_NAMESPACE_ID::uint64 csn_;
  int txn_type_;
  int txn_state_;
  ::PROTOBUF_NAMESPACE_ID::uint64 message_server_id_;
  ::PROTOBUF_NAMESPACE_ID::uint64 shard_id_;
  ::PROTOBUF_NAMESPACE_ID::uint64 shard_server_id_;
  ::PROTOBUF_NAMESPACE_ID::uint64 client_txn_id_;
  ::PROTOBUF_NAMESPACE_ID::uint32 txn_server_id_;
  ::PROTOBUF_NAMESPACE_ID::uint64 storage_total_num_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_transaction_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Column

// uint32 id = 1;
inline void Column::clear_id() {
  id_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Column::_internal_id() const {
  return id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Column::id() const {
  // @@protoc_insertion_point(field_get:proto.Column.id)
  return _internal_id();
}
inline void Column::_internal_set_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  id_ = value;
}
inline void Column::set_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:proto.Column.id)
}

// bytes value = 2;
inline void Column::clear_value() {
  value_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& Column::value() const {
  // @@protoc_insertion_point(field_get:proto.Column.value)
  return _internal_value();
}
inline void Column::set_value(const std::string& value) {
  _internal_set_value(value);
  // @@protoc_insertion_point(field_set:proto.Column.value)
}
inline std::string* Column::mutable_value() {
  // @@protoc_insertion_point(field_mutable:proto.Column.value)
  return _internal_mutable_value();
}
inline const std::string& Column::_internal_value() const {
  return value_.GetNoArena();
}
inline void Column::_internal_set_value(const std::string& value) {
  
  value_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void Column::set_value(std::string&& value) {
  
  value_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:proto.Column.value)
}
inline void Column::set_value(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  value_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:proto.Column.value)
}
inline void Column::set_value(const void* value, size_t size) {
  
  value_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:proto.Column.value)
}
inline std::string* Column::_internal_mutable_value() {
  
  return value_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* Column::release_value() {
  // @@protoc_insertion_point(field_release:proto.Column.value)
  
  return value_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void Column::set_allocated_value(std::string* value) {
  if (value != nullptr) {
    
  } else {
    
  }
  value_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set_allocated:proto.Column.value)
}

// -------------------------------------------------------------------

// Row

// .proto.OpType op_type = 1;
inline void Row::clear_op_type() {
  op_type_ = 0;
}
inline ::proto::OpType Row::_internal_op_type() const {
  return static_cast< ::proto::OpType >(op_type_);
}
inline ::proto::OpType Row::op_type() const {
  // @@protoc_insertion_point(field_get:proto.Row.op_type)
  return _internal_op_type();
}
inline void Row::_internal_set_op_type(::proto::OpType value) {
  
  op_type_ = value;
}
inline void Row::set_op_type(::proto::OpType value) {
  _internal_set_op_type(value);
  // @@protoc_insertion_point(field_set:proto.Row.op_type)
}

// string table_name = 2;
inline void Row::clear_table_name() {
  table_name_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& Row::table_name() const {
  // @@protoc_insertion_point(field_get:proto.Row.table_name)
  return _internal_table_name();
}
inline void Row::set_table_name(const std::string& value) {
  _internal_set_table_name(value);
  // @@protoc_insertion_point(field_set:proto.Row.table_name)
}
inline std::string* Row::mutable_table_name() {
  // @@protoc_insertion_point(field_mutable:proto.Row.table_name)
  return _internal_mutable_table_name();
}
inline const std::string& Row::_internal_table_name() const {
  return table_name_.GetNoArena();
}
inline void Row::_internal_set_table_name(const std::string& value) {
  
  table_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void Row::set_table_name(std::string&& value) {
  
  table_name_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:proto.Row.table_name)
}
inline void Row::set_table_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  table_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:proto.Row.table_name)
}
inline void Row::set_table_name(const char* value, size_t size) {
  
  table_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:proto.Row.table_name)
}
inline std::string* Row::_internal_mutable_table_name() {
  
  return table_name_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* Row::release_table_name() {
  // @@protoc_insertion_point(field_release:proto.Row.table_name)
  
  return table_name_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void Row::set_allocated_table_name(std::string* table_name) {
  if (table_name != nullptr) {
    
  } else {
    
  }
  table_name_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), table_name);
  // @@protoc_insertion_point(field_set_allocated:proto.Row.table_name)
}

// bytes key = 3;
inline void Row::clear_key() {
  key_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& Row::key() const {
  // @@protoc_insertion_point(field_get:proto.Row.key)
  return _internal_key();
}
inline void Row::set_key(const std::string& value) {
  _internal_set_key(value);
  // @@protoc_insertion_point(field_set:proto.Row.key)
}
inline std::string* Row::mutable_key() {
  // @@protoc_insertion_point(field_mutable:proto.Row.key)
  return _internal_mutable_key();
}
inline const std::string& Row::_internal_key() const {
  return key_.GetNoArena();
}
inline void Row::_internal_set_key(const std::string& value) {
  
  key_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void Row::set_key(std::string&& value) {
  
  key_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:proto.Row.key)
}
inline void Row::set_key(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  key_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:proto.Row.key)
}
inline void Row::set_key(const void* value, size_t size) {
  
  key_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:proto.Row.key)
}
inline std::string* Row::_internal_mutable_key() {
  
  return key_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* Row::release_key() {
  // @@protoc_insertion_point(field_release:proto.Row.key)
  
  return key_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void Row::set_allocated_key(std::string* key) {
  if (key != nullptr) {
    
  } else {
    
  }
  key_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), key);
  // @@protoc_insertion_point(field_set_allocated:proto.Row.key)
}

// bytes data = 4;
inline void Row::clear_data() {
  data_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& Row::data() const {
  // @@protoc_insertion_point(field_get:proto.Row.data)
  return _internal_data();
}
inline void Row::set_data(const std::string& value) {
  _internal_set_data(value);
  // @@protoc_insertion_point(field_set:proto.Row.data)
}
inline std::string* Row::mutable_data() {
  // @@protoc_insertion_point(field_mutable:proto.Row.data)
  return _internal_mutable_data();
}
inline const std::string& Row::_internal_data() const {
  return data_.GetNoArena();
}
inline void Row::_internal_set_data(const std::string& value) {
  
  data_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void Row::set_data(std::string&& value) {
  
  data_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:proto.Row.data)
}
inline void Row::set_data(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  data_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:proto.Row.data)
}
inline void Row::set_data(const void* value, size_t size) {
  
  data_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:proto.Row.data)
}
inline std::string* Row::_internal_mutable_data() {
  
  return data_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* Row::release_data() {
  // @@protoc_insertion_point(field_release:proto.Row.data)
  
  return data_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void Row::set_allocated_data(std::string* data) {
  if (data != nullptr) {
    
  } else {
    
  }
  data_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), data);
  // @@protoc_insertion_point(field_set_allocated:proto.Row.data)
}

// repeated .proto.Column column = 5;
inline int Row::_internal_column_size() const {
  return column_.size();
}
inline int Row::column_size() const {
  return _internal_column_size();
}
inline void Row::clear_column() {
  column_.Clear();
}
inline ::proto::Column* Row::mutable_column(int index) {
  // @@protoc_insertion_point(field_mutable:proto.Row.column)
  return column_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::proto::Column >*
Row::mutable_column() {
  // @@protoc_insertion_point(field_mutable_list:proto.Row.column)
  return &column_;
}
inline const ::proto::Column& Row::_internal_column(int index) const {
  return column_.Get(index);
}
inline const ::proto::Column& Row::column(int index) const {
  // @@protoc_insertion_point(field_get:proto.Row.column)
  return _internal_column(index);
}
inline ::proto::Column* Row::_internal_add_column() {
  return column_.Add();
}
inline ::proto::Column* Row::add_column() {
  // @@protoc_insertion_point(field_add:proto.Row.column)
  return _internal_add_column();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::proto::Column >&
Row::column() const {
  // @@protoc_insertion_point(field_list:proto.Row.column)
  return column_;
}

// uint64 csn = 6;
inline void Row::clear_csn() {
  csn_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Row::_internal_csn() const {
  return csn_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Row::csn() const {
  // @@protoc_insertion_point(field_get:proto.Row.csn)
  return _internal_csn();
}
inline void Row::_internal_set_csn(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  csn_ = value;
}
inline void Row::set_csn(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_csn(value);
  // @@protoc_insertion_point(field_set:proto.Row.csn)
}

// -------------------------------------------------------------------

// Transaction

// repeated .proto.Row row = 1;
inline int Transaction::_internal_row_size() const {
  return row_.size();
}
inline int Transaction::row_size() const {
  return _internal_row_size();
}
inline void Transaction::clear_row() {
  row_.Clear();
}
inline ::proto::Row* Transaction::mutable_row(int index) {
  // @@protoc_insertion_point(field_mutable:proto.Transaction.row)
  return row_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::proto::Row >*
Transaction::mutable_row() {
  // @@protoc_insertion_point(field_mutable_list:proto.Transaction.row)
  return &row_;
}
inline const ::proto::Row& Transaction::_internal_row(int index) const {
  return row_.Get(index);
}
inline const ::proto::Row& Transaction::row(int index) const {
  // @@protoc_insertion_point(field_get:proto.Transaction.row)
  return _internal_row(index);
}
inline ::proto::Row* Transaction::_internal_add_row() {
  return row_.Add();
}
inline ::proto::Row* Transaction::add_row() {
  // @@protoc_insertion_point(field_add:proto.Transaction.row)
  return _internal_add_row();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::proto::Row >&
Transaction::row() const {
  // @@protoc_insertion_point(field_list:proto.Transaction.row)
  return row_;
}

// uint64 start_epoch = 2;
inline void Transaction::clear_start_epoch() {
  start_epoch_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Transaction::_internal_start_epoch() const {
  return start_epoch_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Transaction::start_epoch() const {
  // @@protoc_insertion_point(field_get:proto.Transaction.start_epoch)
  return _internal_start_epoch();
}
inline void Transaction::_internal_set_start_epoch(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  start_epoch_ = value;
}
inline void Transaction::set_start_epoch(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_start_epoch(value);
  // @@protoc_insertion_point(field_set:proto.Transaction.start_epoch)
}

// uint64 commit_epoch = 3;
inline void Transaction::clear_commit_epoch() {
  commit_epoch_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Transaction::_internal_commit_epoch() const {
  return commit_epoch_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Transaction::commit_epoch() const {
  // @@protoc_insertion_point(field_get:proto.Transaction.commit_epoch)
  return _internal_commit_epoch();
}
inline void Transaction::_internal_set_commit_epoch(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  commit_epoch_ = value;
}
inline void Transaction::set_commit_epoch(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_commit_epoch(value);
  // @@protoc_insertion_point(field_set:proto.Transaction.commit_epoch)
}

// uint64 csn = 4;
inline void Transaction::clear_csn() {
  csn_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Transaction::_internal_csn() const {
  return csn_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Transaction::csn() const {
  // @@protoc_insertion_point(field_get:proto.Transaction.csn)
  return _internal_csn();
}
inline void Transaction::_internal_set_csn(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  csn_ = value;
}
inline void Transaction::set_csn(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_csn(value);
  // @@protoc_insertion_point(field_set:proto.Transaction.csn)
}

// .proto.TxnType txn_type = 5;
inline void Transaction::clear_txn_type() {
  txn_type_ = 0;
}
inline ::proto::TxnType Transaction::_internal_txn_type() const {
  return static_cast< ::proto::TxnType >(txn_type_);
}
inline ::proto::TxnType Transaction::txn_type() const {
  // @@protoc_insertion_point(field_get:proto.Transaction.txn_type)
  return _internal_txn_type();
}
inline void Transaction::_internal_set_txn_type(::proto::TxnType value) {
  
  txn_type_ = value;
}
inline void Transaction::set_txn_type(::proto::TxnType value) {
  _internal_set_txn_type(value);
  // @@protoc_insertion_point(field_set:proto.Transaction.txn_type)
}

// .proto.TxnState txn_state = 6;
inline void Transaction::clear_txn_state() {
  txn_state_ = 0;
}
inline ::proto::TxnState Transaction::_internal_txn_state() const {
  return static_cast< ::proto::TxnState >(txn_state_);
}
inline ::proto::TxnState Transaction::txn_state() const {
  // @@protoc_insertion_point(field_get:proto.Transaction.txn_state)
  return _internal_txn_state();
}
inline void Transaction::_internal_set_txn_state(::proto::TxnState value) {
  
  txn_state_ = value;
}
inline void Transaction::set_txn_state(::proto::TxnState value) {
  _internal_set_txn_state(value);
  // @@protoc_insertion_point(field_set:proto.Transaction.txn_state)
}

// uint64 message_server_id = 10;
inline void Transaction::clear_message_server_id() {
  message_server_id_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Transaction::_internal_message_server_id() const {
  return message_server_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Transaction::message_server_id() const {
  // @@protoc_insertion_point(field_get:proto.Transaction.message_server_id)
  return _internal_message_server_id();
}
inline void Transaction::_internal_set_message_server_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  message_server_id_ = value;
}
inline void Transaction::set_message_server_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_message_server_id(value);
  // @@protoc_insertion_point(field_set:proto.Transaction.message_server_id)
}

// uint64 shard_id = 11;
inline void Transaction::clear_shard_id() {
  shard_id_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Transaction::_internal_shard_id() const {
  return shard_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Transaction::shard_id() const {
  // @@protoc_insertion_point(field_get:proto.Transaction.shard_id)
  return _internal_shard_id();
}
inline void Transaction::_internal_set_shard_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  shard_id_ = value;
}
inline void Transaction::set_shard_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_shard_id(value);
  // @@protoc_insertion_point(field_set:proto.Transaction.shard_id)
}

// uint64 shard_server_id = 12;
inline void Transaction::clear_shard_server_id() {
  shard_server_id_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Transaction::_internal_shard_server_id() const {
  return shard_server_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Transaction::shard_server_id() const {
  // @@protoc_insertion_point(field_get:proto.Transaction.shard_server_id)
  return _internal_shard_server_id();
}
inline void Transaction::_internal_set_shard_server_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  shard_server_id_ = value;
}
inline void Transaction::set_shard_server_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_shard_server_id(value);
  // @@protoc_insertion_point(field_set:proto.Transaction.shard_server_id)
}

// string txn_server_ip = 13;
inline void Transaction::clear_txn_server_ip() {
  txn_server_ip_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& Transaction::txn_server_ip() const {
  // @@protoc_insertion_point(field_get:proto.Transaction.txn_server_ip)
  return _internal_txn_server_ip();
}
inline void Transaction::set_txn_server_ip(const std::string& value) {
  _internal_set_txn_server_ip(value);
  // @@protoc_insertion_point(field_set:proto.Transaction.txn_server_ip)
}
inline std::string* Transaction::mutable_txn_server_ip() {
  // @@protoc_insertion_point(field_mutable:proto.Transaction.txn_server_ip)
  return _internal_mutable_txn_server_ip();
}
inline const std::string& Transaction::_internal_txn_server_ip() const {
  return txn_server_ip_.GetNoArena();
}
inline void Transaction::_internal_set_txn_server_ip(const std::string& value) {
  
  txn_server_ip_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void Transaction::set_txn_server_ip(std::string&& value) {
  
  txn_server_ip_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:proto.Transaction.txn_server_ip)
}
inline void Transaction::set_txn_server_ip(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  txn_server_ip_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:proto.Transaction.txn_server_ip)
}
inline void Transaction::set_txn_server_ip(const char* value, size_t size) {
  
  txn_server_ip_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:proto.Transaction.txn_server_ip)
}
inline std::string* Transaction::_internal_mutable_txn_server_ip() {
  
  return txn_server_ip_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* Transaction::release_txn_server_ip() {
  // @@protoc_insertion_point(field_release:proto.Transaction.txn_server_ip)
  
  return txn_server_ip_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void Transaction::set_allocated_txn_server_ip(std::string* txn_server_ip) {
  if (txn_server_ip != nullptr) {
    
  } else {
    
  }
  txn_server_ip_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), txn_server_ip);
  // @@protoc_insertion_point(field_set_allocated:proto.Transaction.txn_server_ip)
}

// uint32 txn_server_id = 14;
inline void Transaction::clear_txn_server_id() {
  txn_server_id_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Transaction::_internal_txn_server_id() const {
  return txn_server_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Transaction::txn_server_id() const {
  // @@protoc_insertion_point(field_get:proto.Transaction.txn_server_id)
  return _internal_txn_server_id();
}
inline void Transaction::_internal_set_txn_server_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  txn_server_id_ = value;
}
inline void Transaction::set_txn_server_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_txn_server_id(value);
  // @@protoc_insertion_point(field_set:proto.Transaction.txn_server_id)
}

// string client_ip = 15;
inline void Transaction::clear_client_ip() {
  client_ip_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& Transaction::client_ip() const {
  // @@protoc_insertion_point(field_get:proto.Transaction.client_ip)
  return _internal_client_ip();
}
inline void Transaction::set_client_ip(const std::string& value) {
  _internal_set_client_ip(value);
  // @@protoc_insertion_point(field_set:proto.Transaction.client_ip)
}
inline std::string* Transaction::mutable_client_ip() {
  // @@protoc_insertion_point(field_mutable:proto.Transaction.client_ip)
  return _internal_mutable_client_ip();
}
inline const std::string& Transaction::_internal_client_ip() const {
  return client_ip_.GetNoArena();
}
inline void Transaction::_internal_set_client_ip(const std::string& value) {
  
  client_ip_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void Transaction::set_client_ip(std::string&& value) {
  
  client_ip_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:proto.Transaction.client_ip)
}
inline void Transaction::set_client_ip(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  client_ip_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:proto.Transaction.client_ip)
}
inline void Transaction::set_client_ip(const char* value, size_t size) {
  
  client_ip_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:proto.Transaction.client_ip)
}
inline std::string* Transaction::_internal_mutable_client_ip() {
  
  return client_ip_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* Transaction::release_client_ip() {
  // @@protoc_insertion_point(field_release:proto.Transaction.client_ip)
  
  return client_ip_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void Transaction::set_allocated_client_ip(std::string* client_ip) {
  if (client_ip != nullptr) {
    
  } else {
    
  }
  client_ip_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), client_ip);
  // @@protoc_insertion_point(field_set_allocated:proto.Transaction.client_ip)
}

// uint64 client_txn_id = 16;
inline void Transaction::clear_client_txn_id() {
  client_txn_id_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Transaction::_internal_client_txn_id() const {
  return client_txn_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Transaction::client_txn_id() const {
  // @@protoc_insertion_point(field_get:proto.Transaction.client_txn_id)
  return _internal_client_txn_id();
}
inline void Transaction::_internal_set_client_txn_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  client_txn_id_ = value;
}
inline void Transaction::set_client_txn_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_client_txn_id(value);
  // @@protoc_insertion_point(field_set:proto.Transaction.client_txn_id)
}

// uint64 storage_total_num = 21;
inline void Transaction::clear_storage_total_num() {
  storage_total_num_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Transaction::_internal_storage_total_num() const {
  return storage_total_num_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Transaction::storage_total_num() const {
  // @@protoc_insertion_point(field_get:proto.Transaction.storage_total_num)
  return _internal_storage_total_num();
}
inline void Transaction::_internal_set_storage_total_num(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  storage_total_num_ = value;
}
inline void Transaction::set_storage_total_num(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_storage_total_num(value);
  // @@protoc_insertion_point(field_set:proto.Transaction.storage_total_num)
}

// string storage_type = 22;
inline void Transaction::clear_storage_type() {
  storage_type_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& Transaction::storage_type() const {
  // @@protoc_insertion_point(field_get:proto.Transaction.storage_type)
  return _internal_storage_type();
}
inline void Transaction::set_storage_type(const std::string& value) {
  _internal_set_storage_type(value);
  // @@protoc_insertion_point(field_set:proto.Transaction.storage_type)
}
inline std::string* Transaction::mutable_storage_type() {
  // @@protoc_insertion_point(field_mutable:proto.Transaction.storage_type)
  return _internal_mutable_storage_type();
}
inline const std::string& Transaction::_internal_storage_type() const {
  return storage_type_.GetNoArena();
}
inline void Transaction::_internal_set_storage_type(const std::string& value) {
  
  storage_type_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void Transaction::set_storage_type(std::string&& value) {
  
  storage_type_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:proto.Transaction.storage_type)
}
inline void Transaction::set_storage_type(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  storage_type_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:proto.Transaction.storage_type)
}
inline void Transaction::set_storage_type(const char* value, size_t size) {
  
  storage_type_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:proto.Transaction.storage_type)
}
inline std::string* Transaction::_internal_mutable_storage_type() {
  
  return storage_type_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* Transaction::release_storage_type() {
  // @@protoc_insertion_point(field_release:proto.Transaction.storage_type)
  
  return storage_type_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void Transaction::set_allocated_storage_type(std::string* storage_type) {
  if (storage_type != nullptr) {
    
  } else {
    
  }
  storage_type_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), storage_type);
  // @@protoc_insertion_point(field_set_allocated:proto.Transaction.storage_type)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::proto::Result> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::proto::Result>() {
  return ::proto::Result_descriptor();
}
template <> struct is_proto_enum< ::proto::TxnType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::proto::TxnType>() {
  return ::proto::TxnType_descriptor();
}
template <> struct is_proto_enum< ::proto::TxnState> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::proto::TxnState>() {
  return ::proto::TxnState_descriptor();
}
template <> struct is_proto_enum< ::proto::OpType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::proto::OpType>() {
  return ::proto::OpType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_transaction_2eproto
