// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/client.protofiles

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	pb/client.protofiles
	pb/message.protofiles
	pb/node.protofiles
	pb/person.protofiles
	pb/server.protofiles
	pb/storage.protofiles
	pb/transaction.protofiles

It has these top-level messages:
	ClientReadRequest
	ClientReadResponse
	Message
	Node
	Person
	ReplyTransactionToClient
	RaftRequest
	Ping
	Signal
	LookupMasterRequest
	ForwardEpochRequest
	EpochReplicationAck
	RaftPropose
	RaftAcceptRequest
	RaftCommitRequest
	StatsRequest
	ChangeServerStateRequest
	RaftResponse
	Pong
	MasterMetadata
	KeyMasterMetadata
	LookupMasterResponse
	RaftAcceptResponse
	RaftCommitResponse
	StatsResponse
	ChangeServerStateResponse
	StoragePullRequest
	StoragePullResponse
	StoragePushResponse
	Column
	Row
	Transaction
*/
package taas_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the protofiles package it is being compiled against.
// A compilation error at this line likely means your copy of the
// protofiles package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the protofiles package

type ClientReadRequest struct {
	ClientIp string `protobuf:"bytes,1,opt,name=client_ip,json=clientIp" json:"client_ip,omitempty"`
	TxnId    uint64 `protobuf:"varint,2,opt,name=txn_id,json=txnId" json:"txn_id,omitempty"`
	Rows     []*Row `protobuf:"bytes,3,rep,name=rows" json:"rows,omitempty"`
}

func (m *ClientReadRequest) Reset()                    { *m = ClientReadRequest{} }
func (m *ClientReadRequest) String() string            { return proto.CompactTextString(m) }
func (*ClientReadRequest) ProtoMessage()               {}
func (*ClientReadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ClientReadRequest) GetClientIp() string {
	if m != nil {
		return m.ClientIp
	}
	return ""
}

func (m *ClientReadRequest) GetTxnId() uint64 {
	if m != nil {
		return m.TxnId
	}
	return 0
}

func (m *ClientReadRequest) GetRows() []*Row {
	if m != nil {
		return m.Rows
	}
	return nil
}

type ClientReadResponse struct {
	Result Result `protobuf:"varint,1,opt,name=result,enum=pb.Result" json:"result,omitempty"`
	TxnId  uint64 `protobuf:"varint,2,opt,name=txn_id,json=txnId" json:"txn_id,omitempty"`
	Rows   []*Row `protobuf:"bytes,3,rep,name=rows" json:"rows,omitempty"`
}

func (m *ClientReadResponse) Reset()                    { *m = ClientReadResponse{} }
func (m *ClientReadResponse) String() string            { return proto.CompactTextString(m) }
func (*ClientReadResponse) ProtoMessage()               {}
func (*ClientReadResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ClientReadResponse) GetResult() Result {
	if m != nil {
		return m.Result
	}
	return Result_Fail
}

func (m *ClientReadResponse) GetTxnId() uint64 {
	if m != nil {
		return m.TxnId
	}
	return 0
}

func (m *ClientReadResponse) GetRows() []*Row {
	if m != nil {
		return m.Rows
	}
	return nil
}

func init() {
	proto.RegisterType((*ClientReadRequest)(nil), "pb.ClientReadRequest")
	proto.RegisterType((*ClientReadResponse)(nil), "pb.ClientReadResponse")
}

func init() { proto.RegisterFile("pb/client.protofiles", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 197 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x8f, 0xcd, 0x6a, 0x85, 0x30,
	0x10, 0x85, 0xf1, 0xa7, 0xb6, 0x4e, 0x69, 0x4b, 0x43, 0x0b, 0xa2, 0x1b, 0x71, 0xe5, 0x4a, 0xc1,
	0x3e, 0x42, 0x57, 0x6e, 0xf3, 0x02, 0x62, 0x4c, 0x16, 0x01, 0x49, 0xa6, 0xc9, 0x88, 0x3e, 0x7e,
	0x21, 0xb9, 0x8b, 0xbb, 0xbe, 0xcb, 0xf9, 0x0e, 0x67, 0x3e, 0x0e, 0x7c, 0xa0, 0x18, 0xb7, 0x5d,
	0x2b, 0x43, 0x03, 0x3a, 0x4b, 0x96, 0xa5, 0x28, 0xea, 0x2f, 0x14, 0x23, 0xb9, 0xd5, 0xf8, 0x75,
	0x23, 0x6d, 0x4d, 0x4c, 0xea, 0x37, 0x14, 0xa3, 0xb1, 0x52, 0xc5, 0xb3, 0x93, 0xf0, 0xf9, 0x1b,
	0x8a, 0x5c, 0xad, 0x92, 0xab, 0xbf, 0x43, 0x79, 0x62, 0x0d, 0x94, 0xf1, 0xdb, 0xa2, 0xb1, 0x4a,
	0xda, 0xa4, 0x2f, 0xf9, 0x4b, 0x04, 0x33, 0xb2, 0x6f, 0x28, 0xe8, 0x32, 0x8b, 0x96, 0x55, 0xda,
	0x26, 0x7d, 0xce, 0x9f, 0xe8, 0x32, 0xb3, 0x64, 0x0d, 0xe4, 0xce, 0x9e, 0xbe, 0xca, 0xda, 0xac,
	0x7f, 0x9d, 0x9e, 0x07, 0x14, 0x03, 0xb7, 0x27, 0x0f, 0xb0, 0xdb, 0x81, 0xdd, 0x5b, 0x3c, 0x5a,
	0xe3, 0x15, 0xeb, 0xa0, 0x70, 0xca, 0x1f, 0x3b, 0x05, 0xc7, 0xfb, 0x04, 0xa1, 0x14, 0x08, 0xbf,
	0x25, 0x8f, 0xd8, 0x44, 0x11, 0xa6, 0xfd, 0xfc, 0x07, 0x00, 0x00, 0xff, 0xff, 0x2f, 0x24, 0x70,
	0x54, 0x16, 0x01, 0x00, 0x00,
}
